[package]
name = "nv1-hub-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-graphics = "0.8.1"
num-traits = { version = "0.2.19", default-features = false }

[features]
no_std = []
default = []
